#!/bin/sh

# ci_post_clone.sh
# Xcode Cloud runs this automatically after cloning the repository.
# It generates Keys.swift from environment variables so secrets stay out of the repo.
#
# Required Xcode Cloud environment variables:
# MIXPANEL_TOKEN

set -e

KEYS_FILE="${CI_PRIMARY_REPOSITORY_PATH}/AIChatCourse/Utilities/Keys.swift"

echo '//' > "$KEYS_FILE"
echo '// Keys.swift' >> "$KEYS_FILE"
echo '// AIChatCourse' >> "$KEYS_FILE"
echo '//' >> "$KEYS_FILE"
echo '// Auto-generated by ci_post_clone.sh' >> "$KEYS_FILE"
echo '//' >> "$KEYS_FILE"
echo '' >> "$KEYS_FILE"
echo 'struct Keys {' >> "$KEYS_FILE"
echo " static let mixpanelToken = \"${MIXPANEL_TOKEN}\"" >> "$KEYS_FILE"
echo '}' >> "$KEYS_FILE"

echo "Keys.swift generated at $KEYS_FILE"


